주문조회, 배송조회 API 추가
JINSEO0201/SNU_GraduART_Backend pull request #7
Opened 2024-11-10 11:42 UTC by JINSEO0201

[Description]
purchased table은 각 item에 대응되는 결제기록, 
order_info는 주문 건수에 대응되는 기록으로 만들었습니당

예를 들어, 한 번의 주문으로 A와 B 상품을 주문했다면
order_info에는 하나의 row가 추가되며 이는 이 주문 건에 대해 주문자에 대한 정보를 저장합니다. (주소, 이름, 이메일, 전화번호)
purchased에는 두 개의 row가 추가되며 이는 앞서 추가된 order_info의 id를 foreign key로 가지고 있습니다. 결제에 대한 정보를 담고 있어요..!

따라서 purchased table의 id (int) 를 가지고 조회를 하는 일이 많을 것이고, purchased table의 foreign key 중 item_id는 unique, user_id와 order_id는 unique하지 않습니다!

[제안 사항]
1. url 마지막에 / 없으면 자동으로 추가해주는 옵션을 넣고 싶어요 아마 장고에서 지원했던 것 같은데, 굳이 없어도 되는건지 궁금합니다 넣는거 좋으면 제가 찾아서 다음 PR에 넣을게요!

2. 위 설명에 따라 purchased table의 price는 total_price보단 price가 나을 것 같고 order_info에 total_price가 들어가는게 나을 것 같아요 
일단 DB 구조 보고 피드백 해보고 이대로 가는게 괜찮으면 결정하면 될 것 같슴다

2024-11-10 18:14 UTC, minseo25 commented
테이블 구조 이해 완료했습니다~~

1. url 뒤에 / 없으면 자동으로 추가해주는 옵션 있으면 좋은데, 차피 백엔드 api는 프론트 코드 상에서 하드코딩(?) 되는거라 굳이 필요 없을 듯함! / 없어서 에러 나면 프론트 개발자가 그냥 코드에 / 추가해주면 끝나는 문제니까

2. 지금 테이블 구조라면 너말대로 purchased에서 order_info로 (total_price, payment_method, card_info) 이런 결제 관련 컬럼들을 옮기는 게 좋을 듯? 대신 is_confirmed나 refund의 경우는 item 별로 확정을 다르게 지을 수 있으니까 purchased 테이블에 남겨놓아야 할 듯해요

3. purchased table의 item_id는 코드를 봐보시면 items의 items_id와 연결되어있지 않고 num_code와 연결되어있음요 (기존 프론트 코드도 그렇고, 그걸 바탕으로 작성한 purchases/views.py 도 그렇고). 따라서 지금 외래키 연결이 잘못되어잇음 (int 타입의 num_code와 연동되어야 함)
=> 근데 이건 item_id(uuid) 놔두고 왜 굳이 별도로 작품별로 num_code 두었는지 물어봐야될 듯

2024-11-10 18:14 UTC, minseo25 commented on SNU_GraduART/settings.py
> +    'order',
order 앱이 없는데?

2024-11-10 18:18 UTC, minseo25 commented on delivery/views.py
> +    user_requested = supabase.table("purchased").select("user_id").eq("purchased_id", purchased_id).execute()
purchased_id 라는 컬럼이 테이블에 없음

2024-11-10 18:20 UTC, minseo25 commented on delivery/views.py
> +    user_requested = supabase.table("purchased").select("user_id").eq("purchased_id", purchased_id).execute()
아마 id 라는 primary key를 가져오려 했겠지?

2024-11-10 18:24 UTC, minseo25 commented on delivery/views.py
> +    purchased_id = request.data.get("purchased_id")
일단 운송장번호를 조회할 때 purchased table의 primary key(id)를 프론트에서 알 방법이 없음. 설사 백에서 건네주면 되지 않느냐라고 하더라도 아무 의미가 담겨있지 않은 id 값을 넘겨줄 이유는 없음.

따라서 purchased 테이블에서 record를 식별할 수 있는 조합을 생각해보면 (프론트단에서 가지고 있는 정보만으로) item_id가 있겠죠

그러면 일단 item_id를 받으면 => 해당 사용자의 user_id 와 item_id 조합으로 purchased 테이블에서 레코드 있는지 파악, refund 되었는지 안됐는지 파악

refund 안됐다면 거기서 id를 가져오고, 그 id를 가지고 delivery page를 조회

이런 흐름으로 가야겠죠?

2024-11-10 18:27 UTC, minseo25 commented on delivery/views.py
> +    redirect_url = f"https://www.google.com/search?q={courier_name}+{tracking_num}"
구글도 좋은데, 이렇게만 되면 url로 이동 후 배송추적 버튼을 한 번 더 눌러야하는 번거로움이 존재.
네이버든 뭐든 url 로 접속 시 배송조회 페이지가 한 번에 뜨는 url을 찾으면 좋을 것 같음 (네이버는 한 번에 되네요)

![image](https://github.com/user-attachments/assets/9daa30ed-7909-4b03-b03f-aa0891fef18c)

2024-11-10 18:27 UTC, minseo25 requested changes
반영해서 고쳐주세요~~

2024-11-11 03:31 UTC, JINSEO0201 commented on delivery/views.py
> +    user_requested = supabase.table("purchased").select("user_id").eq("purchased_id", purchased_id).execute()
헉 맞네요 수정할게여

2024-11-11 03:49 UTC, JINSEO0201 commented on delivery/views.py
> +    purchased_id = request.data.get("purchased_id")
배송조회가 구매내역 조회에서 이어지는 흐름이라 purchased table의 id를 가지고 있다고 생각하긴 했는데, 생각해보니 의미가 없는 id값이긴 하네.. get_purchases view에서 id를 전달할 이유가 없는거구나 애초에 

item_id 받는걸로 수정해볼게여

근데 refund 여부로 배송조회가 달라지는 것은 굳이 안 해두 되지 않을까여

2024-11-11 08:07 UTC, minseo25 commented on delivery/views.py
> +    if user_id != purchased_info[0]['user_id']:
만약 어떤 item_id 에 대한 purchased_info 가 없다면
purchased_info[0] 하는 과정에서 에러 뜰 거 같긴한데 일단 로직 자체는 맞으니까 테스팅하면서 수정합시다요

2024-11-11 08:08 UTC, minseo25 commented on delivery/views.py
> +    redirect_url = f"https://search.naver.com/search.naver?query={courier_name}{tracking_num}"
잘되네요 굿

2024-11-11 08:12 UTC, minseo25 commented on purchases/views.py
> +
자동으로 구매확정되는 코드를 api로 만들어놓는다해도 그 api를 호출하지 않는 이상 실행될 일이 없을 것 같아 (이건 백그라운드에서 실행되는 별도의 프로그램이 필요한 부분이니까)
이거는 purchases 에서 만들기보다 환불요청에서 하는 게 좋지 않을까?

구매확정 state를 별도로 관리하는 게 아니라, 환불요청 들어왔을 때 구매확정 기간이 지났는지 안지났는지 검증하는 형태로 말야!

2024-11-11 08:21 UTC, minseo25 approved these changes

2024-11-11 08:56 UTC, merged

2024-11-11 15:36 UTC, JINSEO0201 commented on purchases/views.py
> +
이거가 약간 꼼수인데, 일단 원하는 건 환불요청 버튼을 만들어두고 눌렀을 때 거절하는 방식을 조금 넘어서 환불 요청 버튼을 아예 잠구고 싶어. 비동기 작업은 설정하기 귀찮고 구매확정 state는 관리해야하니까..  

환불요청을 하려고 들어가는 길에 구매내역 조회(마이페이지)를 거치니까, 구매내역 불러올 때마다 빠르게 쭉 점검하는 식으로 로직을 넣어두려고 했어. 환불 요청 들어왔을 때도 물론 검증하고 거절하는 코드 들어가고. 

서비스 확장하면 비동기 작업 처리하면 되는데 지금은 어차피 row도 몇 개 안 돼서(이미 구매를 마친 유저와 상품들에 한정) 저 로직 계속 작동시켜도 별 차이 없겠단 판단 하에 써둔 거긴 합니당..!